### ISSUE TITLE
Minor typo on README.md

### ISSUE THREAD

**Issue by MathijsVerbeeck** [Adam-it/cli-for-microsoft-365-extension#6]
Hi Adam

I've noticed that there is a typo on the README.md page. 

The current solution (extension) is in prototype **faze** so may not have regular releases.

I do believe that 'faze' should be replaced with **phase** 😃.

Great extension!

**Comment by Adam-it** [comment]
hahaha.. thanks for noticing that 👍 You rock 👍
🤔 probably I was really tired coding late hours ... like now 😉.

**Comment by Adam-it** [comment]
fixed with direct commit.
thanks @MathijsVerbeeck for your contribution 👍
